
import React, { useState, useEffect, useCallback } from 'react';
import { SolverMode, Solution, HistoryItem, UserPlan } from './types';
import { MODES } from './constants';
import { getAiSolution } from './services/geminiService';

// Components
const Header: React.FC = () => (
  <header className="fixed top-0 w-full bg-white/80 backdrop-blur-md border-b z-50">
    <div className="max-w-7xl mx-auto px-4 h-16 flex items-center justify-between">
      <div className="flex items-center gap-2">
        <div className="w-10 h-10 bg-indigo-600 rounded-xl flex items-center justify-center text-white font-bold text-xl">S</div>
        <span className="text-xl font-bold text-slate-900">SolveIt AI</span>
      </div>
      <nav className="hidden md:flex gap-6 text-sm font-medium text-slate-600">
        <a href="#features" className="hover:text-indigo-600 transition-colors">Features</a>
        <a href="#pricing" className="hover:text-indigo-600 transition-colors">Pricing</a>
        <a href="#dashboard" className="hover:text-indigo-600 transition-colors">My Solutions</a>
      </nav>
      <button className="bg-slate-900 text-white px-5 py-2 rounded-full text-sm font-semibold hover:bg-slate-800 transition-all shadow-lg shadow-indigo-100">
        Upgrade to Pro
      </button>
    </div>
  </header>
);

const Footer: React.FC = () => (
  <footer className="bg-slate-50 border-t py-12">
    <div className="max-w-7xl mx-auto px-4 text-center">
      <div className="flex justify-center gap-2 mb-6">
        <div className="w-8 h-8 bg-indigo-600 rounded-lg flex items-center justify-center text-white font-bold text-sm">S</div>
        <span className="text-lg font-bold">SolveIt AI</span>
      </div>
      <p className="text-slate-500 text-sm max-w-md mx-auto mb-8">
        Helping 1.4 Billion people solve problems using AI. Desi solutions for Desi problems.
      </p>
      <div className="text-slate-400 text-xs">
        © 2024 SolveIt AI India. All rights reserved.
      </div>
    </div>
  </footer>
);

const App: React.FC = () => {
  const [problem, setProblem] = useState('');
  const [selectedMode, setSelectedMode] = useState<SolverMode>(SolverMode.GENERAL);
  const [loading, setLoading] = useState(false);
  const [currentSolution, setCurrentSolution] = useState<Solution | null>(null);
  const [history, setHistory] = useState<HistoryItem[]>([]);
  const [plan, setPlan] = useState<UserPlan>({ type: 'FREE', queriesRemaining: 3 });
  const [copySuccess, setCopySuccess] = useState(false);

  // Load history from local storage
  useEffect(() => {
    const saved = localStorage.getItem('solveit_history');
    if (saved) setHistory(JSON.parse(saved));
    
    const savedPlan = localStorage.getItem('solveit_plan');
    if (savedPlan) setPlan(JSON.parse(savedPlan));
  }, []);

  const handleSolve = async () => {
    if (!problem.trim()) return;
    if (plan.queriesRemaining <= 0 && plan.type === 'FREE') {
      alert("Daily limit reached! Upgrade to Pro for unlimited solutions.");
      return;
    }

    setLoading(true);
    setCurrentSolution(null);
    try {
      const solution = await getAiSolution(problem, selectedMode);
      setCurrentSolution(solution);
      
      const newHistoryItem: HistoryItem = {
        id: Math.random().toString(36).substr(2, 9),
        problem,
        mode: selectedMode,
        solution,
        timestamp: Date.now()
      };
      
      const updatedHistory = [newHistoryItem, ...history].slice(0, 10);
      setHistory(updatedHistory);
      localStorage.setItem('solveit_history', JSON.stringify(updatedHistory));
      
      const updatedPlan: UserPlan = { ...plan, queriesRemaining: Math.max(0, plan.queriesRemaining - 1) };
      setPlan(updatedPlan);
      localStorage.setItem('solveit_plan', JSON.stringify(updatedPlan));

    } catch (error) {
      console.error(error);
      alert("Something went wrong. Please check your internet connection.");
    } finally {
      setLoading(false);
    }
  };

  const copyToClipboard = async () => {
    if (!currentSolution) return;

    const textToCopy = `
SolveIt AI - Solution Report
Problem: ${problem}

ANALYSIS:
${currentSolution.analysis}

ACTIONABLE STEPS:
${currentSolution.steps.map((s, i) => `${i + 1}. ${s}`).join('\n')}

DESI EXAMPLES:
${currentSolution.indianExamples.map(e => `• ${e}`).join('\n')}

GROWTH HACKS:
${currentSolution.growthHacks.map(h => `⚡ ${h}`).join('\n')}

RESOURCES:
${currentSolution.resources.map(r => `${r.name}: ${r.link} (${r.description})`).join('\n')}

ESTIMATED TIME: ${currentSolution.estimatedTime}
NEXT STEPS:
${currentSolution.nextActions.map(a => `✅ ${a}`).join('\n')}

Generated by SolveIt AI
    `.trim();

    try {
      await navigator.clipboard.writeText(textToCopy);
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2000);
    } catch (err) {
      console.error('Failed to copy!', err);
    }
  };

  return (
    <div className="min-h-screen pt-16 flex flex-col">
      <Header />

      <main className="flex-grow">
        {/* Hero Section */}
        <section className="py-16 md:py-24 px-4 bg-gradient-to-b from-indigo-50/50 to-white overflow-hidden relative">
          <div className="absolute -top-24 -right-24 w-96 h-96 bg-indigo-200 rounded-full blur-3xl opacity-20"></div>
          <div className="absolute bottom-0 -left-24 w-96 h-96 bg-purple-200 rounded-full blur-3xl opacity-20"></div>

          <div className="max-w-4xl mx-auto text-center relative">
            <h1 className="text-4xl md:text-6xl font-extrabold text-slate-900 mb-6 leading-tight">
              Har Problem Ka <span className="gradient-text">AI Solution</span> <br />
              <span className="text-3xl md:text-5xl">Sirf 30 Seconds Me</span>
            </h1>
            <p className="text-lg text-slate-600 mb-10 max-w-2xl mx-auto">
              Solving for Bharat: YouTube growth, Career confusion, Paisa kamane ke plans, and Life hacks — powered by Google Gemini.
            </p>

            {/* Input Box */}
            <div className="bg-white p-2 rounded-2xl shadow-xl border border-indigo-100 flex flex-col md:flex-row gap-2 max-w-3xl mx-auto">
              <input
                type="text"
                placeholder="Ex: 'Mujhe YouTube channel grow karna hai' or 'Study stress kaise manage kare?'"
                className="flex-grow px-6 py-4 text-lg focus:outline-none rounded-xl"
                value={problem}
                onChange={(e) => setProblem(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleSolve()}
              />
              <button
                onClick={handleSolve}
                disabled={loading}
                className="bg-indigo-600 text-white px-8 py-4 rounded-xl font-bold text-lg hover:bg-indigo-700 transition-all flex items-center justify-center gap-2 disabled:opacity-50"
              >
                {loading ? (
                  <div className="w-6 h-6 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
                ) : (
                  <>Solve It <span className="text-2xl">⚡</span></>
                )}
              </button>
            </div>

            {/* Daily Counter */}
            <p className="mt-4 text-sm font-medium text-slate-400">
              Free queries left today: <span className="text-indigo-600">{plan.queriesRemaining}</span>
            </p>

            {/* Mode Selectors */}
            <div className="mt-12">
              <p className="text-sm font-semibold text-slate-500 uppercase tracking-wider mb-4">Select Your Mode</p>
              <div className="flex flex-wrap justify-center gap-3">
                {MODES.map((mode) => (
                  <button
                    key={mode.id}
                    onClick={() => setSelectedMode(mode.id)}
                    className={`flex items-center gap-2 px-5 py-3 rounded-full border-2 transition-all ${
                      selectedMode === mode.id
                        ? `border-indigo-600 bg-indigo-50 text-indigo-700 shadow-md`
                        : 'border-transparent bg-white text-slate-600 hover:border-slate-200 shadow-sm'
                    }`}
                  >
                    <span>{mode.icon}</span>
                    <span className="font-semibold">{mode.label}</span>
                  </button>
                ))}
              </div>
            </div>
          </div>
        </section>

        {/* Results Section */}
        {currentSolution && !loading && (
          <section className="py-12 px-4 bg-white" id="solution">
            <div className="max-w-4xl mx-auto bg-slate-50 rounded-3xl border border-slate-200 overflow-hidden shadow-2xl">
              {/* Solution Header */}
              <div className="bg-indigo-600 p-8 text-white">
                <div className="flex justify-between items-start mb-4">
                  <span className="bg-white/20 px-3 py-1 rounded-full text-xs font-bold uppercase tracking-widest">
                    AI Solved This
                  </span>
                  <div className="flex gap-2">
                    <button 
                      onClick={copyToClipboard}
                      title="Copy full solution"
                      className="flex items-center gap-2 bg-white/10 hover:bg-white/20 text-white px-4 py-2 rounded-lg transition-colors text-sm font-semibold border border-white/10"
                    >
                       {copySuccess ? (
                         <>
                           <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"></path></svg>
                           Copied!
                         </>
                       ) : (
                         <>
                           <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3"></path></svg>
                           Copy Solution
                         </>
                       )}
                    </button>
                  </div>
                </div>
                <h2 className="text-2xl font-bold mb-2">Solution Plan</h2>
                <p className="opacity-90">{currentSolution.analysis}</p>
              </div>

              {/* Solution Content */}
              <div className="p-8 space-y-10">
                {/* Steps */}
                <div>
                  <h3 className="text-xl font-bold text-slate-900 mb-6 flex items-center gap-3">
                    <span className="w-8 h-8 bg-indigo-100 text-indigo-600 rounded-full flex items-center justify-center text-sm">01</span>
                    Actionable Steps
                  </h3>
                  <div className="grid gap-4">
                    {currentSolution.steps.map((step, idx) => (
                      <div key={idx} className="flex gap-4 items-start p-4 bg-white rounded-2xl border border-slate-100 shadow-sm">
                        <div className="mt-1 w-2 h-2 rounded-full bg-indigo-500 shrink-0"></div>
                        <p className="text-slate-700">{step}</p>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Indian Examples & Hacks */}
                <div className="grid md:grid-cols-2 gap-8">
                  <div className="bg-orange-50 p-6 rounded-2xl border border-orange-100">
                    <h4 className="font-bold text-orange-900 mb-4 flex items-center gap-2">
                      <span>🇮🇳</span> Desi Examples
                    </h4>
                    <ul className="space-y-3">
                      {currentSolution.indianExamples.map((ex, idx) => (
                        <li key={idx} className="text-sm text-orange-800 flex items-start gap-2">
                          <span className="mt-1.5 w-1 h-1 bg-orange-400 rounded-full shrink-0"></span>
                          {ex}
                        </li>
                      ))}
                    </ul>
                  </div>
                  <div className="bg-pink-50 p-6 rounded-2xl border border-pink-100">
                    <h4 className="font-bold text-pink-900 mb-4 flex items-center gap-2">
                      <span>🚀</span> Growth Hacks
                    </h4>
                    <ul className="space-y-3">
                      {currentSolution.growthHacks.map((hack, idx) => (
                        <li key={idx} className="text-sm text-pink-800 flex items-start gap-2">
                          <span className="mt-1.5 w-1 h-1 bg-pink-400 rounded-full shrink-0"></span>
                          {hack}
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>

                {/* Resources */}
                <div>
                  <h3 className="text-xl font-bold text-slate-900 mb-6 flex items-center gap-3">
                    <span className="w-8 h-8 bg-indigo-100 text-indigo-600 rounded-full flex items-center justify-center text-sm">02</span>
                    Recommended Tools & Resources
                  </h3>
                  <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
                    {currentSolution.resources.map((res, idx) => (
                      <div key={idx} className="p-4 bg-white border border-slate-100 rounded-2xl hover:shadow-md transition-all group">
                        <p className="font-bold text-indigo-600 mb-1">{res.name}</p>
                        <p className="text-xs text-slate-500 mb-3">{res.description}</p>
                        <a href={res.link} target="_blank" className="text-xs font-semibold text-slate-900 group-hover:underline flex items-center gap-1">
                          View Resource ↗
                        </a>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Final Call to Action */}
                <div className="bg-slate-900 text-white p-8 rounded-2xl flex flex-col md:flex-row items-center justify-between gap-6">
                  <div>
                    <h4 className="text-xl font-bold mb-1">Estimated Results In: {currentSolution.estimatedTime}</h4>
                    <p className="text-slate-400 text-sm">Start with these 2 actions today:</p>
                  </div>
                  <div className="flex flex-col gap-2 w-full md:w-auto">
                    {currentSolution.nextActions.slice(0, 2).map((act, idx) => (
                      <div key={idx} className="bg-white/10 px-4 py-2 rounded-lg text-sm font-medium">
                        ✅ {act}
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </section>
        )}

        {/* Dashboard/History (Simple View) */}
        {history.length > 0 && (
          <section className="py-20 px-4 bg-slate-50" id="dashboard">
            <div className="max-w-7xl mx-auto">
              <div className="flex justify-between items-end mb-10">
                <div>
                  <h2 className="text-3xl font-bold text-slate-900">Recently Solved</h2>
                  <p className="text-slate-500">Your history of problems solved by SolveIt AI.</p>
                </div>
                <button 
                  onClick={() => { localStorage.removeItem('solveit_history'); setHistory([]); }}
                  className="text-sm font-medium text-red-600 hover:underline"
                >
                  Clear History
                </button>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {history.map((item) => (
                  <div 
                    key={item.id} 
                    className="bg-white p-6 rounded-3xl border border-slate-200 shadow-sm hover:shadow-lg transition-all cursor-pointer group"
                    onClick={() => {
                      setCurrentSolution(item.solution);
                      setProblem(item.problem);
                      setSelectedMode(item.mode);
                      window.scrollTo({ top: document.getElementById('solution')?.offsetTop || 0, behavior: 'smooth' });
                    }}
                  >
                    <div className="flex justify-between mb-4">
                       <span className="text-xs font-bold text-indigo-600 uppercase bg-indigo-50 px-2 py-1 rounded">
                         {item.mode}
                       </span>
                       <span className="text-[10px] text-slate-400 uppercase">
                         {new Date(item.timestamp).toLocaleDateString()}
                       </span>
                    </div>
                    <p className="font-bold text-slate-800 line-clamp-2 mb-4 group-hover:text-indigo-600">
                      "{item.problem}"
                    </p>
                    <div className="flex items-center gap-2 text-xs font-semibold text-slate-400">
                      View full solution <span>→</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </section>
        )}

        {/* Features/Stats Section */}
        <section className="py-24 px-4" id="features">
          <div className="max-w-7xl mx-auto grid md:grid-cols-2 gap-16 items-center">
            <div className="relative">
              <div className="aspect-square bg-indigo-100 rounded-[3rem] overflow-hidden rotate-3">
                 <img src="https://picsum.photos/800/800?random=1" alt="AI solving" className="object-cover w-full h-full" />
              </div>
              <div className="absolute -bottom-8 -right-8 bg-white p-6 rounded-3xl shadow-2xl border border-slate-100 max-w-xs animate-bounce-slow">
                <div className="flex gap-4 items-center">
                  <div className="w-12 h-12 bg-green-500 rounded-full flex items-center justify-center text-white">✨</div>
                  <div>
                    <p className="text-sm font-bold text-slate-900">Success Rate: 98%</p>
                    <p className="text-xs text-slate-500">Trusted by 10k+ Creators</p>
                  </div>
                </div>
              </div>
            </div>
            <div>
              <span className="text-indigo-600 font-bold uppercase tracking-widest text-sm mb-4 block">How it works</span>
              <h2 className="text-4xl font-extrabold text-slate-900 mb-8">One AI for every Desi problem.</h2>
              <div className="space-y-6">
                {[
                  { title: "Smart Desi Intelligence", desc: "Our AI understands Hinglish and local context better than anyone else." },
                  { title: "Actionable over Generic", desc: "No more long paragraphs. Get step-by-step checklists and resources." },
                  { title: "Speed is Everything", desc: "Get complex career or growth problems solved in under 30 seconds." }
                ].map((f, i) => (
                  <div key={i} className="flex gap-4">
                    <div className="w-10 h-10 bg-indigo-100 rounded-xl flex items-center justify-center text-indigo-600 shrink-0 font-bold">
                      {i + 1}
                    </div>
                    <div>
                      <h4 className="font-bold text-slate-900 mb-1">{f.title}</h4>
                      <p className="text-slate-500 text-sm">{f.desc}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>

        {/* Pricing Section */}
        <section className="py-24 px-4 bg-indigo-600" id="pricing">
          <div className="max-w-7xl mx-auto text-center text-white">
            <h2 className="text-4xl font-extrabold mb-4">No Problem is Too Big</h2>
            <p className="opacity-80 mb-16">Choose the plan that fits your growth.</p>
            
            <div className="grid md:grid-cols-2 max-w-4xl mx-auto gap-8">
              {/* Free Plan */}
              <div className="bg-white/10 backdrop-blur-md p-10 rounded-[2.5rem] border border-white/20 text-left">
                <h3 className="text-2xl font-bold mb-2">Bharat Free</h3>
                <p className="text-white/60 mb-8 text-sm">For testing the waters.</p>
                <div className="text-4xl font-bold mb-8">₹0 <span className="text-lg font-normal opacity-60">/month</span></div>
                <ul className="space-y-4 mb-10 text-sm">
                  <li className="flex gap-2">✅ 3 AI queries daily</li>
                  <li className="flex gap-2">✅ Hinglish support</li>
                  <li className="flex gap-2">✅ Basic checklists</li>
                </ul>
                <button className="w-full py-4 rounded-2xl bg-white text-indigo-600 font-bold hover:bg-indigo-50 transition-all">
                  Current Plan
                </button>
              </div>

              {/* Pro Plan */}
              <div className="bg-white p-10 rounded-[2.5rem] text-left relative overflow-hidden">
                <div className="absolute top-6 right-6 bg-indigo-600 text-white text-[10px] font-bold px-3 py-1 rounded-full uppercase tracking-widest animate-pulse">
                  Trending
                </div>
                <h3 className="text-2xl font-bold text-slate-900 mb-2">Creator Pro</h3>
                <p className="text-slate-500 mb-8 text-sm">For serious creators & solopreneurs.</p>
                <div className="text-4xl font-bold text-slate-900 mb-8">₹499 <span className="text-lg font-normal text-slate-400">/month</span></div>
                <ul className="space-y-4 mb-10 text-sm text-slate-600">
                  <li className="flex gap-2 font-bold text-indigo-600">✨ Unlimited queries</li>
                  <li className="flex gap-2">✅ Deep business analytics</li>
                  <li className="flex gap-2">✅ Priority prompt packs</li>
                  <li className="flex gap-2">✅ Custom AI strategy</li>
                </ul>
                <button className="w-full py-4 rounded-2xl bg-indigo-600 text-white font-bold hover:bg-indigo-700 transition-all shadow-xl shadow-indigo-200">
                  Upgrade Now
                </button>
              </div>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
};

export default App;
